endpoints:
  env:
    keys-to-santize: password,proxy
spring:
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
server:
  tomcat:
    baseDir: .
    accesslog:
      enabled: true
      buffered: false
