

DROP TABLE IF EXISTS USER_ROLE_DOMAIN;
DROP TABLE IF EXISTS  ROLE_PERM;
DROP TABLE IF EXISTS  ROLE;
DROP TABLE IF EXISTS  PERM;

CREATE TABLE USER_ROLE_DOMAIN (
   ID INT PRIMARY KEY     NOT NULL,
   USER_NAME TEXT NOT NULL,
   ROLE_NAME TEXT NOT NULL,
   DOMAIN    TEXT NOT NULL
);



CREATE TABLE ROLE (
   ROLE_NAME TEXT PRIMARY KEY,
   ROLE_DESCRIPTION TEXT NOT NULL
);



CREATE TABLE PERM (
   PERM_NAME TEXT PRIMARY KEY,
   PERM_DESCRIPTION TEXT NOT NULL
);

CREATE TABLE ROLE_PERM (
   ID INT PRIMARY KEY     NOT NULL,
   ROLE_NAME TEXT references ROLE(ROLE_NAME), 
   PERM_NAME TEXT references PERM(PERM_NAME)
);

