fin

DROP TABLE IF EXISTS USER_ROLE_DOMAIN;
DROP TABLE IF EXISTS ROLE_PERM;
DROP TABLE IF EXISTS PERMISSION;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS DOMAIN;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER {
   USER_ID TEXT NOT Null,
   LOGIN_NAME TEXT NOT NULL,
   PASSWORD_VALUE TEXT NOT NULL,
   FIRST_NAME TEXT NOT NULL,
   LAST_NAME TEXT NOT  NULL,
   EMAIL TEXT NOT NULL,
   CONFIRM_VALUE TEXT NOT NULL,
   MODIFED TIMESTAMP,
   CREATED TIMESTAMP,
   LAST_LOGIN TIMESTAMP,
}

CREATE TABLE DOMAIN {
   DOMAIN_ID integer PRIMARY KEY,
   DOMAIN_NAME TEXT,
}

CREATE TABLE ROLE (
   ROLE_ID INTEGER PRIMARY KEY,
   ROLE_NAME TEXT NOT NULL,
);

CREATE TABLE PERMISSION (
   PERMISSION_ID INTEGER PRIMARY KEY,
   PERMISSION_NAME TEXT NOT NULL,
);

CREATE TABLE ROLE_PERM (
   ROLE_ID TEXT references ROLE(ROLE_ID),
   PERMISSION_ID TEXT references PERMISSION(PERM_ID)
);

CREATE TABLE USER_ROLE_DOMAIN (
   USER_ID integer NOT NULL,
   ROLE_ID integer NOT NULL,
   DOMAIN_ID integer NOT NULL
);

